# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               5square | Automation // API // Smart Home
tagline:             no idea
url:                 https://5square.github.io/
baseurl:             "/"

# About/contact
author:
  name:              Jan Burkl
  url:               https://www.5square.de
  email:             jan@5square.de

# Custom vars
version:             2.0.0
#github:
#  repo:              https://github.com/5square/www.5square.de

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
  - webrick
